#ifndef RT_CONFIG_H__
#define RT_CONFIG_H__

/* Generated by Kconfiglib (https://github.com/ulfalizer/Kconfiglib) */
#define BSP_USING_RETRO_GO
#define BSP_RETRO_GO_ROM_DIR "/sdcard/roms"
#define BSP_RETRO_GO_ROM_PATH ""
#define BSP_RETRO_GO_SAVE_DIR "/sdcard/retro-go/saves"
#define BSP_RETRO_GO_SD_MOUNT_TIMEOUT_MS 30000
#define BSP_RETRO_GO_SCALE_FIT
#define BSP_RETRO_GO_USE_VGLITE
#define BSP_RETRO_GO_MAX_FRAME_SKIP 2
#define BSP_RETRO_GO_GBA_MAX_FRAME_SKIP 1
#define BSP_RETRO_GO_GBA_LATE_SKIP_US 6000
#define BSP_RETRO_GO_GBA_MIN_DRAW_FRAMES_AFTER_SKIP 2
#define BSP_RETRO_GO_MAX_ROMS 64
#define BSP_RETRO_GO_CJK_MENU
#define BSP_RETRO_GO_GB_BOOT_BIOS
#define BSP_RETRO_GO_GB_BIOS_PATH "/sdcard/retro-go/bios/gb_bios.bin"
#define BSP_RETRO_GO_GBC_BIOS_PATH "/sdcard/retro-go/bios/gbc_bios.bin"
#define BSP_RETRO_GO_GBA
#define BSP_RETRO_GO_GBA_ROM_CACHE_MB 7
#define BSP_RETRO_GO_GBA_AUDIO_MIX_KHZ 16
#define BSP_RETRO_GO_GBA_PERF_STATS
#define BSP_RETRO_GO_GBA_DEEP_PROFILE
#define BSP_RETRO_GO_GBA_ARM_AL_FASTPATH
#define BSP_RETRO_GO_GBA_LAZY_CPSR_WRITEBACK
#define BSP_RETRO_GO_GBA_DIRECT_SCANOUT
#define BSP_RETRO_GO_GBA_FLIP_WAIT_MS 3
#define BSP_RETRO_GO_PERF_OVERLAY
#define BSP_RETRO_GO_PERF_UPDATE_MS 1000
#define BSP_RETRO_GO_DWT_TIMING
#define BSP_RETRO_GO_M55_BRANCH_PREDICTION
#define BSP_RETRO_GO_AUDIO
#define BSP_RETRO_GO_AUDIO_BACKEND_PDL
#define BSP_RETRO_GO_AUDIO_PREROLL_SAMPLES 2048
#define BSP_RETRO_GO_AUDIO_CONTINUITY_LINEAR
#define BSP_RETRO_GO_AUDIO_VARISPEED
#define BSP_RETRO_GO_AUDIO_WSOLA
#define BSP_RETRO_GO_AUDIO_WSOLA_GRAIN_SAMPLES 512
#define BSP_RETRO_GO_AUDIO_WSOLA_SEARCH_SAMPLES 96
#define BSP_RETRO_GO_AUDIO_OUTPUT_TARGET_SAMPLES 3584
#define BSP_RETRO_GO_AUDIO_TARGET_SAMPLES 1536
#define BSP_RETRO_GO_AUDIO_BUFFER_CORRECTION_PERCENT 12
#define BSP_RETRO_GO_AUDIO_MIN_SPEED_PERCENT 25
#define BSP_RETRO_GO_AUDIO_RATE_WINDOW_MS 250
#define BSP_RETRO_GO_AUDIO_STARTUP_RATE_WINDOW_MS 50
#define BSP_RETRO_GO_AUDIO_CONCEAL_FADE_MS 10
#define BSP_RETRO_GO_INPUT_THREAD_PRIORITY 24
#define BSP_RETRO_GO_INPUT_RELEASE_TIMEOUT_MS 1000
#define BSP_RETRO_GO_AUTOSAVE_SECONDS 0
#define BSP_RETRO_GO_HYPERRAM_WRITEBACK_CACHE
#define SOC_SERIES_IFX_PSOCE84
#define KIT_PROCE84_EVK_M55
#define BSP_USING_USB_TO_UART
#define BSP_USING_LCD
#define COMPONENT_MTB_DISPLAY_tl043wvv02
#define M55_BSP_LCD_ROTATION_90
#define BSP_LCD_ROTATION_90
#define BSP_LCD_ROTATION_DEGREES 90
#define BSP_LCD_ROTATION_BACKEND_VGLITE
#define BSP_LCD_USE_AXIDMAC_AREA_COPY
#define BSP_LCD_AXIDMAC_AREA_COPY_MIN_BYTES 8192
#define BSP_USING_GPIO
#define BSP_USING_I2C
#define BSP_USING_HW_I2C0
#define BSP_USING_UART
#define BSP_USING_UART2
#define BSP_USING_HYPERAM
#define BSP_USING_HYPERAM_SIZE 0x800000
#define BSP_USING_PWM
#define BSP_USING_PWM18
#define BSP_USING_SDIO
#define BSP_USING_SDIO1
#define BSP_USING_FILESYSTEM
#define BSP_USING_SDCARD
#define CONFIG_USBHOST_PSC_PRIO 23
#define RT_MAIN_THREAD_PRIORITY 25
#define RT_MAIN_THREAD_STACK_SIZE 16384

/* RT-Thread Kernel */

#define RT_NAME_MAX 8
#define RT_ALIGN_SIZE 8
#define RT_THREAD_PRIORITY_32
#define RT_THREAD_PRIORITY_MAX 32
#define RT_TICK_PER_SECOND 1000
#define RT_USING_OVERFLOW_CHECK
#define RT_USING_HOOK
#define RT_HOOK_USING_FUNC_PTR
#define RT_USING_IDLE_HOOK
#define RT_IDLE_HOOK_LIST_SIZE 4
#define IDLE_THREAD_STACK_SIZE 1024
#define RT_USING_TIMER_SOFT
#define RT_TIMER_THREAD_PRIO 4
#define RT_TIMER_THREAD_STACK_SIZE 2048

/* kservice optimization */

#define RT_KSERVICE_USING_STDLIB
/* end of kservice optimization */
#define RT_USING_DEBUG
#define RT_DEBUGING_COLOR
#define RT_DEBUGING_CONTEXT

/* Inter-Thread communication */

#define RT_USING_SEMAPHORE
#define RT_USING_MUTEX
#define RT_USING_EVENT
#define RT_USING_MAILBOX
#define RT_USING_MESSAGEQUEUE
/* end of Inter-Thread communication */

/* Memory Management */

#define RT_USING_MEMPOOL
#define RT_USING_SMALL_MEM
#define RT_USING_MEMHEAP
#define RT_MEMHEAP_FAST_MODE
#define RT_USING_MEMHEAP_AS_HEAP
#define RT_USING_MEMHEAP_AUTO_BINDING
#define RT_USING_HEAP
/* end of Memory Management */

/* Kernel Device Object */

#define RT_USING_DEVICE
#define RT_USING_CONSOLE
#define RT_CONSOLEBUF_SIZE 1024
#define RT_CONSOLE_DEVICE_NAME "uart2"
/* end of Kernel Device Object */
#define RT_VER_NUM 0x50002
/* end of RT-Thread Kernel */
#define RT_USING_CACHE

/* RT-Thread Components */

#define RT_USING_COMPONENTS_INIT
#define RT_USING_USER_MAIN
#define RT_USING_MSH
#define RT_USING_FINSH
#define FINSH_USING_MSH
#define FINSH_THREAD_NAME "tshell"
#define FINSH_THREAD_PRIORITY 20
#define FINSH_THREAD_STACK_SIZE 4096
#define FINSH_USING_HISTORY
#define FINSH_HISTORY_LINES 5
#define FINSH_USING_SYMTAB
#define FINSH_CMD_SIZE 80
#define MSH_USING_BUILT_IN_COMMANDS
#define FINSH_USING_DESCRIPTION
#define FINSH_ARG_MAX 10
#define FINSH_USING_OPTION_COMPLETION

/* DFS: device virtual file system */

#define RT_USING_DFS
#define DFS_USING_POSIX
#define DFS_USING_WORKDIR
#define DFS_FD_MAX 16
#define RT_USING_DFS_V1
#define DFS_FILESYSTEMS_MAX 4
#define DFS_FILESYSTEM_TYPES_MAX 4
#define RT_USING_DFS_ELMFAT

/* elm-chan's FatFs, Generic FAT Filesystem Module */

#define RT_DFS_ELM_CODE_PAGE 437
#define RT_DFS_ELM_WORD_ACCESS
#define RT_DFS_ELM_USE_LFN_3
#define RT_DFS_ELM_USE_LFN 3
#define RT_DFS_ELM_LFN_UNICODE_2
#define RT_DFS_ELM_LFN_UNICODE 2
#define RT_DFS_ELM_MAX_LFN 255
#define RT_DFS_ELM_DRIVES 2
#define RT_DFS_ELM_MAX_SECTOR_SIZE 512
#define RT_DFS_ELM_REENTRANT
#define RT_DFS_ELM_MUTEX_TIMEOUT 3000
/* end of elm-chan's FatFs, Generic FAT Filesystem Module */
#define RT_USING_DFS_DEVFS
#define RT_USING_DFS_ROMFS
/* end of DFS: device virtual file system */

/* Device Drivers */

#define RT_USING_DEVICE_IPC
#define RT_UNAMED_PIPE_NUMBER 64
#define RT_USING_SERIAL
#define RT_USING_SERIAL_V1
#define RT_SERIAL_USING_DMA
#define RT_SERIAL_RB_BUFSZ 128
#define RT_USING_I2C
#define RT_USING_PIN
#define RT_USING_PWM
#define RT_USING_RTC
#define RT_USING_SOFT_RTC
#define RT_USING_SDIO
#define RT_SDIO_STACK_SIZE 512
#define RT_SDIO_THREAD_PRIORITY 15
#define RT_MMCSD_STACK_SIZE 2048
#define RT_MMCSD_THREAD_PREORITY 22
#define RT_MMCSD_MAX_PARTITION 16
#define RT_USING_LCD

/* Using USB */

/* end of Using USB */
/* end of Device Drivers */

/* C/C++ and POSIX layer */

/* ISO-ANSI C layer */

/* Timezone and Daylight Saving Time */

#define RT_LIBC_USING_LIGHT_TZ_DST
#define RT_LIBC_TZ_DEFAULT_HOUR 8
#define RT_LIBC_TZ_DEFAULT_MIN 0
#define RT_LIBC_TZ_DEFAULT_SEC 0
/* end of Timezone and Daylight Saving Time */
/* end of ISO-ANSI C layer */

/* POSIX (Portable Operating System Interface) layer */

#define RT_USING_POSIX_FS

/* Interprocess Communication (IPC) */


/* Socket is in the 'Network' category */

/* end of Interprocess Communication (IPC) */
/* end of POSIX (Portable Operating System Interface) layer */
/* end of C/C++ and POSIX layer */

/* Network */

/* end of Network */

/* Utilities */

/* end of Utilities */
/* end of RT-Thread Components */

/* RT-Thread Utestcases */

/* end of RT-Thread Utestcases */
#define RT_USING_CHERRYUSB
#define RT_CHERRYUSB_HOST
#define RT_CHERRYUSB_HOST_DWC2_INFINEON
#define RT_CHERRYUSB_HOST_HID
#define CONFIG_USBHOST_PSC_STACKSIZE 4096
#define CONFIG_USBHOST_REQUEST_BUFFER_LEN 512
#define CONFIG_USBHOST_CONTROL_TRANSFER_TIMEOUT 500
#define CONFIG_USBHOST_SERIAL_RX_SIZE 2048
#define RT_LWIP_PBUF_POOL_BUFSIZE 1600

/* Select USB host template, please select class driver first */

#define RT_TEST_USBH_HID 0
/* end of Select USB host template, please select class driver first */

#endif
