from building import *

cwd = GetCurrentDir()
src = Glob('*.c')
path = [
    cwd,
    cwd + '/../sdlpal/upstream',
    cwd + '/../sdlpal/upstream/sdl_compat',
    cwd + '/../sdlpal/upstream/esp32s3/native_engine_shim/include',
    cwd + '/../../../libraries/HAL_Drivers',
]

group = DefineGroup('SDLPalPlatform', src, depend=[''], CPPPATH=path)

Return('group')
