from building import *

cwd = GetCurrentDir()
src = Glob('*.c')
path = [
    cwd,
    cwd + '/../sdlpal/upstream',
    cwd + '/../sdlpal/upstream/sdl_compat',
    cwd + '/../sdlpal/upstream/esp32s3/native_engine_shim/include',
    cwd + '/../../../libraries/HAL_Drivers',
]

if GetDepend(['BSP_SDLPAL_INPUT_TOUCH']):
    src = [item for item in src
           if item not in Glob('pal_usb_keyboard_*.c')]
elif GetDepend(['BSP_SDLPAL_INPUT_USB_KEYBOARD']):
    src = [item for item in src if item not in Glob('pal_touch_*.c')]
    path += [
        cwd + '/../../../libraries/Common/board/ports/usb',
        cwd + '/../../../libraries/components/CherryUSB-1.6.0/common',
        cwd + '/../../../libraries/components/CherryUSB-1.6.0/core',
        cwd + '/../../../libraries/components/CherryUSB-1.6.0/class/hid',
    ]
else:
    raise RuntimeError('Select exactly one SDLPal input mode')

group = DefineGroup('SDLPalPlatform', src, depend=[''], CPPPATH=path)

Return('group')
